name: neuprint-python
channels:
  - flyem-forge
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38_1000
  - asciitree=0.3.3=py_2
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - bokeh=1.4.0=py38_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38_0
  - cffi=1.13.2=py38h33e799b_0
  - chardet=3.0.4=py38_1003
  - colorcet=2.0.1=py_0
  - cryptography=2.8=py38hafa8578_1
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_1000
  - freetype=2.10.0=h24853df_1
  - holoviews=1.12.7=py_0
  - hvplot=0.5.2=py_0
  - idna=2.8=py38_1000
  - importlib_metadata=1.5.0=py38_0
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.2.0=py38_0
  - jupyter_client=5.3.4=py38_1
  - jupyter_core=4.6.2=py38_0
  - kiwisolver=1.1.0=py38ha1b3eb9_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx=9.0.1=1
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h3d69b6c_7
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.17=h01d97ff_0
  - libtiff=4.1.0=ha78913b_3
  - llvm-openmp=9.0.1=h28b9765_2
  - lz4-c=1.8.3=h6de7cb9_1001
  - markupsafe=1.1.1=py38h0b31af3_0
  - matplotlib-base=3.1.3=py38h11da6c2_0
  - mistune=0.8.4=py38h0b31af3_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=h0a44026_1002
  - neuprint-python=0.3.6=py_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38hde6bac1_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h0b31af3_0
  - packaging=20.1=py_0
  - pandas=1.0.1=py38h4f17bb1_0
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - param=1.9.3=py_0
  - parso=0.6.1=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38h918e99a_0
  - pip=20.0.2=py_2
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.19=py38_1
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.15.7=py38h0b31af3_0
  - pysocks=1.7.1=py38_0
  - python=3.8.1=hf2284b6_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.3=py_0
  - pyyaml=5.3=py38h0b31af3_0
  - pyzmq=18.1.1=py38h4bf09a9_0
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py38_1
  - send2trash=1.5.0=py_0
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.30.1=h93121df_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.3=py38h0b31af3_3
  - tqdm=4.42.1=py_0
  - traitlets=4.3.3=py38_0
  - ujson=1.35=py38h0b31af3_1001
  - urllib3=1.25.7=py38_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.2.2=h0b31af3_1
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.4=he7fca8b_1
prefix: /opt/miniconda/envs/neuprint-python

